"""add_phone_and_workplace_to_users

Revision ID: 574e15ccd7bd
Revises: 8c098dccca32
Create Date: 2026-04-21 05:38:11.617007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574e15ccd7bd'
down_revision = '8c098dccca32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('workplace', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('workplace')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
