"""add indexes to foreign keys and search columns

Revision ID: 8c098dccca32
Revises: b766974919d9
Create Date: 2026-04-19 21:29:25.499370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c098dccca32'
down_revision = 'b766974919d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advances_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_advances_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_status'), ['status'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_settlement_id'), ['settlement_id'], unique=False)

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_advance_id'), ['advance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_user_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_status'))
        batch_op.drop_index(batch_op.f('ix_settlements_advance_id'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_settlement_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_category_id'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_status'))
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advances_user_id'))
        batch_op.drop_index(batch_op.f('ix_advances_status'))

    # ### end Alembic commands ###
