"""tambah tabel asosiasi multi kategori

Revision ID: a7e218c38417
Revises: 
Create Date: 2026-04-18 17:48:20.963558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e218c38417'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_subcategories',
        sa.Column('expense_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
        sa.PrimaryKeyConstraint('expense_id', 'category_id')
    )
    op.create_table('advance_item_subcategories',
        sa.Column('advance_item_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['advance_item_id'], ['advance_items.id'], ),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('advance_item_id', 'category_id')
    )
    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_expense_advance_item', 'advance_items', ['advance_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expense_advance_item', type_='foreignkey')

    with op.batch_alter_table('advances', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    op.drop_table('advance_item_subcategories')
    op.drop_table('expense_subcategories')
    # ### end Alembic commands ###
